# Generated by Django 4.0.6 on 2022-11-24 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todos',
            old_name='desc',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='todos',
            old_name='title',
            new_name='summary',
        ),
        migrations.RemoveField(
            model_name='todos',
            name='created',
        ),
        migrations.RemoveField(
            model_name='todos',
            name='datecompleted',
        ),
        migrations.RemoveField(
            model_name='todos',
            name='file',
        ),
        migrations.RemoveField(
            model_name='todos',
            name='priority',
        ),
        migrations.AlterField(
            model_name='todos',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
